### PR TITLE
HTML workshop - Chastity Castro

### PR DESCRIPTION
**Pull request by Chascas**

### CODE REVIEW

**Comment by phides-code** [comment]
Great job, but we'll need a correction: 

For Ex 5, the image does not appear.

(Note, you will reach 75% by fixing Ex 5.. The stuff below is only required if you want 100%) 

For Ex 8:
* it should not be possible to submit the form if all inputs are not specified. 
* Pickup location list is empty.
* Your text field right above the submit button should be a different type of input. Hint: Google "textarea"

Just a comment for Q12, (nothing to do here), an img element must have a src attribute.

Otherwise, great job, just some small corrections to do!

**Comment by Chascas** [comment]
Thank you!

I was wondering by when should I submit a correction?

**Comment by ChinemeremEze** [comment]
Great job again! You reached 75% mark but ex 5 image still needs to be revisited to get 100%

**Comment by Chascas** [comment]
Thank you David!

**Comment by gtomp93** [comment]
Now at 100% with image fix

**Pull request closed without merging**
