### PR TITLE
html workshop Abdul

### PR DESCRIPTION
**Pull request by AbdulDadou**

### CODE REVIEW

**Comment by ChinemeremEze** [comment]
Unfortunately you didn’t reach the 75% mark, you have to use the right element in the right places eg using h2 were p is required, also revisit exercise 5 to ensure your image is visible.

**Comment by AbdulDadou** [comment]
Hello,

I am aware of shortcomings when it comes to workshops. I have had very hard first 2 days because I have 0 background in programming. Was just trying to get to understand what was going on.

Today, I will focus on finishing today's workshop and will use the weekend to cover the backlog for workshops 1 and 2.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ChinemeremEze** [comment]
Hi Abdul,

I have to give it to you, for someone with no background in programming
what so ever, you did really great, just little corrections here and there
to make you a pro in HTML with that said don’t slack because there are new
learning materials everyday so revisit this workshop, try yo get to 75% by
correcting the issues mentioned and move on to what’s needed. Great job so
far!

**Comment by AbdulDadou** [comment]
Thank you. I appreciate your support. It is very important that I don't fall behind on the workshops. It is my chance to learn. I know that I have to give this course 150% to make it to the working force. I better use my time after hours navigating the internet. I found w3school and mozilla to be very helpful.

Regards.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
